### ISSUE TITLE
Visibility TypeError

### ISSUE THREAD

**Issue by Oh-JongJin** [sijung21/js06#24]
```bash
[000001ee3b9ae790] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001ee3b9af2c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
QWindowsWindow::setGeometry: Unable to set geometry 942x393+9+9 (frame: 942x393+9+9) on QWidgetWindow/"QFrameClassWindow" on "\\.\DISPLAY2". Resulting geometry: 942x393+969+85 (frame: 942x393+969+85) margins: 0, 0, 0, 0)
Process producer:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\nd01\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\User\anaconda3\envs\nd01\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Workspace\update_ui\src\video_thread_mp.py", line 63, in producer
    visibility_front = target_info.minprint(epoch[:-2], rear_left_range, rear_right_range,
  File "D:\Workspace\update_ui\src\target_info.py", line 18, in minprint
    result = minrgb(upper_left, lower_right, cp_image)
  File "D:\Workspace\update_ui\src\target_info.py", line 45, in minrgb
    t_idx = np.where(sum_rgb == np.min(sum_rgb))
  File "<__array_function__ internals>", line 180, in amin
  File "C:\Users\User\anaconda3\envs\nd01\lib\site-packages\numpy\core\fromnumeric.py", line 2916, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "C:\Users\User\anaconda3\envs\nd01\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by Oh-JongJin** [comment]
## ValueError: zero-size array to reduction operation minimum which has no identity
It occurs when the image is cropped or resized and the coordinate value suitable for the image is not given.
